import { useState } from "react";
import type { Applicant } from "../types";

export const useApplicants = () => {
  const [applicants] = useState<Applicant[]>([
    {
      id: "1",
      name: "Kim Miller",
      role: "UI/UX Designer",
      appliedOn: "23-07-2025",
      resumeUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      profileImage: "https://randomuser.me/api/portraits/women/1.jpg",
      email: "kim@email.com",
      phone: "+91 789 654 3210",
      experience: "6 Years",
      qualification: "MCA/COM",
      currentLocation: "Ernakulam, Kochi",
    },
        {
      id: "2",
      name: "Kim Miller",
      role: "Full Stack Developer",
      appliedOn: "23-07-2025",
      resumeUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      profileImage: "https://randomuser.me/api/portraits/women/1.jpg",
      email: "kim@email.com",
      phone: "+91 789 654 3210",
      experience: "6 Years",
      qualification: "MCA/COM",
      currentLocation: "Ernakulam, Kochi",
    },
        {
      id: "3",
      name: "Kim Miller",
      role: "UI/UX Designer",
      appliedOn: "23-07-2025",
      resumeUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      profileImage: "https://randomuser.me/api/portraits/women/1.jpg",
      email: "kim@email.com",
      phone: "+91 789 654 3210",
      experience: "6 Years",
      qualification: "MCA/COM",
      currentLocation: "Ernakulam, Kochi",
    },
        {
      id: "4",
      name: "Kim Miller",
      role: "UI/UX Designer",
      appliedOn: "23-07-2025",
      resumeUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      profileImage: "https://randomuser.me/api/portraits/women/1.jpg",
      email: "kim@email.com",
      phone: "+91 789 654 3210",
      experience: "6 Years",
      qualification: "MCA/COM",
      currentLocation: "Ernakulam, Kochi",
    },
        {
      id: "5",
      name: "Kim Miller",
      role: "UI/UX Designer",
      appliedOn: "23-07-2025",
      resumeUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      profileImage: "https://randomuser.me/api/portraits/women/1.jpg",
      email: "kim@email.com",
      phone: "+91 789 654 3210",
      experience: "6 Years",
      qualification: "MCA/COM",
      currentLocation: "Ernakulam, Kochi",
    },
        {
      id: "6",
      name: "Kim Miller",
      role: "UI/UX Designer",
      appliedOn: "23-07-2025",
      resumeUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      profileImage: "https://randomuser.me/api/portraits/women/1.jpg",
      email: "kim@email.com",
      phone: "+91 789 654 3210",
      experience: "6 Years",
      qualification: "MCA/COM",
      currentLocation: "Ernakulam, Kochi",
    },
        {
      id: "7",
      name: "D Miller",
      role: "Developer",
      appliedOn: "23-07-2025",
      resumeUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      profileImage: "https://randomuser.me/api/portraits/women/1.jpg",
      email: "kim@email.com",
      phone: "+91 789 654 3210",
      experience: "6 Years",
      qualification: "MCA/COM",
      currentLocation: "Ernakulam, Kochi",
    },
  ]);

  const getApplicantById = (id: string) => applicants.find((a) => a.id === id);

  return { applicants, getApplicantById };
};
